services:
  meteor:
    build:
      context: ./meteor/
      dockerfile: Dockerfile
    image: alloy4fun-meteor:latest
    ports:
      - "3010:3000"
    links:
      - api
    env_file:
      - .env
  api:
    build:
      context: ./api/
    image: alloy4fun-api:latest
    ports:
      - "8081:8080" # if access is needed from the outside (otherwise no need)
